// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.nexus.rest.model;

/**
 * Class NexusResponse.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
public class NexusResponse
    implements java.io.Serializable
{
}
