// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.nexus.rest.model;

/**
 * Permissions that are granted to the user.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@javax.xml.bind.annotation.XmlType( name = "nexus-authentication-client-permissions" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class NexusAuthenticationClientPermissions
    extends org.sonatype.security.rest.model.AuthenticationClientPermissions
    implements java.io.Serializable
{
}
