// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.nexus.rest.model;

/**
 * REST Response object for the nexus status, contains the typical
 * 'data' parameter, which is the nexus status.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@com.thoughtworks.xstream.annotations.XStreamAlias( value = "status" )
@javax.xml.bind.annotation.XmlRootElement( name = "status" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class StatusResourceResponse
    extends NexusResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Nexus status details.
     */
    private StatusResource data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get nexus status details.
     * 
     * @return StatusResource
     */
    public StatusResource getData()
    {
        return this.data;
    } //-- StatusResource getData()

    /**
     * Set nexus status details.
     * 
     * @param data
     */
    public void setData( StatusResource data )
    {
        this.data = data;
    } //-- void setData( StatusResource )

}
