// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.nexus.rest.model;

/**
 * Configuration validation status.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@javax.xml.bind.annotation.XmlType( name = "status-configuration-validation-response" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class StatusConfigurationValidationResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Flag that states if the nexus configuration is valid.
     */
    private boolean valid = false;

    /**
     * Flag that states if nexus had to modify the nexus
     * configuration.
     */
    private boolean modified = false;

    /**
     * Field validationErrors.
     */
    @javax.xml.bind.annotation.XmlElementWrapper( name = "validationErrors" )
    @javax.xml.bind.annotation.XmlElement( name = "error" )
    private java.util.List<String> validationErrors;

    /**
     * Field validationWarnings.
     */
    @javax.xml.bind.annotation.XmlElementWrapper( name = "validationWarnings" )
    @javax.xml.bind.annotation.XmlElement( name = "warning" )
    private java.util.List<String> validationWarnings;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addValidationError.
     * 
     * @param string
     */
    public void addValidationError( String string )
    {
        getValidationErrors().add( string );
    } //-- void addValidationError( String )

    /**
     * Method addValidationWarning.
     * 
     * @param string
     */
    public void addValidationWarning( String string )
    {
        getValidationWarnings().add( string );
    } //-- void addValidationWarning( String )

    /**
     * Method getValidationErrors.
     * 
     * @return List
     */
    public java.util.List<String> getValidationErrors()
    {
        if ( this.validationErrors == null )
        {
            this.validationErrors = new java.util.ArrayList<String>();
        }

        return this.validationErrors;
    } //-- java.util.List<String> getValidationErrors()

    /**
     * Method getValidationWarnings.
     * 
     * @return List
     */
    public java.util.List<String> getValidationWarnings()
    {
        if ( this.validationWarnings == null )
        {
            this.validationWarnings = new java.util.ArrayList<String>();
        }

        return this.validationWarnings;
    } //-- java.util.List<String> getValidationWarnings()

    /**
     * Get flag that states if nexus had to modify the nexus
     * configuration.
     * 
     * @return boolean
     */
    public boolean isModified()
    {
        return this.modified;
    } //-- boolean isModified()

    /**
     * Get flag that states if the nexus configuration is valid.
     * 
     * @return boolean
     */
    public boolean isValid()
    {
        return this.valid;
    } //-- boolean isValid()

    /**
     * Method removeValidationError.
     * 
     * @param string
     */
    public void removeValidationError( String string )
    {
        getValidationErrors().remove( string );
    } //-- void removeValidationError( String )

    /**
     * Method removeValidationWarning.
     * 
     * @param string
     */
    public void removeValidationWarning( String string )
    {
        getValidationWarnings().remove( string );
    } //-- void removeValidationWarning( String )

    /**
     * Set flag that states if nexus had to modify the nexus
     * configuration.
     * 
     * @param modified
     */
    public void setModified( boolean modified )
    {
        this.modified = modified;
    } //-- void setModified( boolean )

    /**
     * Set flag that states if the nexus configuration is valid.
     * 
     * @param valid
     */
    public void setValid( boolean valid )
    {
        this.valid = valid;
    } //-- void setValid( boolean )

    /**
     * Set list of configuration validation errors.
     * 
     * @param validationErrors
     */
    public void setValidationErrors( java.util.List<String> validationErrors )
    {
        this.validationErrors = validationErrors;
    } //-- void setValidationErrors( java.util.List )

    /**
     * Set list of configuration validation warnings.
     * 
     * @param validationWarnings
     */
    public void setValidationWarnings( java.util.List<String> validationWarnings )
    {
        this.validationWarnings = validationWarnings;
    } //-- void setValidationWarnings( java.util.List )

}
