/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-2015 Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.nexus.restlet1x.model;

/**
 * Login details info.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class AuthenticationClientPermissions
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Flags if a user is logged in.
     */
    private boolean loggedIn = false;

    /**
     * The logged in user's id.
     */
    private String loggedInUsername;

    /**
     * The logged in user's source.
     */
    private String loggedInUserSource;

    /**
     * Field permissions.
     */
    @javax.xml.bind.annotation.XmlElementWrapper( name = "permissions" )
    @javax.xml.bind.annotation.XmlElement( name = "permission" )
    private java.util.List<ClientPermission> permissions;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Method addPermission.
     * 
     * @param clientPermission
     */
    public void addPermission( ClientPermission clientPermission )
    {
        getPermissions().add( clientPermission );
    } //-- void addPermission( ClientPermission )

    /**
     * Get the logged in user's source.
     * 
     * @return String
     */
    public String getLoggedInUserSource()
    {
        return this.loggedInUserSource;
    } //-- String getLoggedInUserSource()

    /**
     * Get the logged in user's id.
     * 
     * @return String
     */
    public String getLoggedInUsername()
    {
        return this.loggedInUsername;
    } //-- String getLoggedInUsername()

    /**
     * Method getPermissions.
     * 
     * @return List
     */
    public java.util.List<ClientPermission> getPermissions()
    {
        if ( this.permissions == null )
        {
            this.permissions = new java.util.ArrayList<ClientPermission>();
        }

        return this.permissions;
    } //-- java.util.List<ClientPermission> getPermissions()

    /**
     * Get flags if a user is logged in.
     * 
     * @return boolean
     */
    public boolean isLoggedIn()
    {
        return this.loggedIn;
    } //-- boolean isLoggedIn()

    /**
     * Method removePermission.
     * 
     * @param clientPermission
     */
    public void removePermission( ClientPermission clientPermission )
    {
        getPermissions().remove( clientPermission );
    } //-- void removePermission( ClientPermission )

    /**
     * Set flags if a user is logged in.
     * 
     * @param loggedIn
     */
    public void setLoggedIn( boolean loggedIn )
    {
        this.loggedIn = loggedIn;
    } //-- void setLoggedIn( boolean )

    /**
     * Set the logged in user's source.
     * 
     * @param loggedInUserSource
     */
    public void setLoggedInUserSource( String loggedInUserSource )
    {
        this.loggedInUserSource = loggedInUserSource;
    } //-- void setLoggedInUserSource( String )

    /**
     * Set the logged in user's id.
     * 
     * @param loggedInUsername
     */
    public void setLoggedInUsername( String loggedInUsername )
    {
        this.loggedInUsername = loggedInUsername;
    } //-- void setLoggedInUsername( String )

    /**
     * Set lists of privileges.
     * 
     * @param permissions
     */
    public void setPermissions( java.util.List<ClientPermission> permissions )
    {
        this.permissions = permissions;
    } //-- void setPermissions( java.util.List )

}
