/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-2015 Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.nexus.restlet1x.model;

/**
 * REST Response object for the nexus status, contains the typical
 * 'data' parameter, which is the nexus status.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@com.thoughtworks.xstream.annotations.XStreamAlias( value = "status" )
@javax.xml.bind.annotation.XmlRootElement( name = "status" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class StatusResourceResponse
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Nexus status details.
     */
    private StatusResource data;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get nexus status details.
     * 
     * @return StatusResource
     */
    public StatusResource getData()
    {
        return this.data;
    } //-- StatusResource getData()

    /**
     * Set nexus status details.
     * 
     * @param data
     */
    public void setData( StatusResource data )
    {
        this.data = data;
    } //-- void setData( StatusResource )

}
