// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.security.rest.model;

/**
 * Wrapper around login details.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class AuthenticationLoginResource
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Login details info.
     */
    private AuthenticationClientPermissions clientPermissions;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get login details info.
     * 
     * @return AuthenticationClientPermissions
     */
    public AuthenticationClientPermissions getClientPermissions()
    {
        return this.clientPermissions;
    } //-- AuthenticationClientPermissions getClientPermissions()

    /**
     * Set login details info.
     * 
     * @param clientPermissions
     */
    public void setClientPermissions( AuthenticationClientPermissions clientPermissions )
    {
        this.clientPermissions = clientPermissions;
    } //-- void setClientPermissions( AuthenticationClientPermissions )

}
