/*
 * Sonatype Nexus (TM) Open Source Version
 * Copyright (c) 2008-2015 Sonatype, Inc.
 * All rights reserved. Includes the third-party code listed at http://links.sonatype.com/products/nexus/oss/attributions.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse Public License Version 1.0,
 * which accompanies this distribution and is available at http://www.eclipse.org/legal/epl-v10.html.
 *
 * Sonatype Nexus (TM) Professional Version is available from Sonatype, Inc. "Sonatype" and "Sonatype Nexus" are trademarks
 * of Sonatype, Inc. Apache Maven is a trademark of the Apache Software Foundation. M2eclipse is a trademark of the
 * Eclipse Foundation. All other trademarks are the property of their respective owners.
 */
// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.security.rest.model;

/**
 * Permission details.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class ClientPermission
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Id of the permission.
     */
    private String id;

    /**
     * Privilege value: NONE = 0, READ = 1, UPDATE = 2, DELETE = 4,
     * CREATE = 8, or you can OR them together.
     */
    private int value = 0;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get id of the permission.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get privilege value: NONE = 0, READ = 1, UPDATE = 2, DELETE
     * = 4, CREATE = 8, or you can OR them together.
     * 
     * @return int
     */
    public int getValue()
    {
        return this.value;
    } //-- int getValue()

    /**
     * Set id of the permission.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set privilege value: NONE = 0, READ = 1, UPDATE = 2, DELETE
     * = 4, CREATE = 8, or you can OR them together.
     * 
     * @param value
     */
    public void setValue( int value )
    {
        this.value = value;
    } //-- void setValue( int )

}
