// =================== DO NOT EDIT THIS FILE ====================
// Generated by Modello 1.7,
// any modifications will be overwritten.
// ==============================================================

package org.sonatype.security.rest.model;

/**
 * Permission details.
 * 
 * @version $Revision$ $Date$
 */
@SuppressWarnings( "all" )
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class ClientPermission
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Id of the permission.
     */
    private String id;

    /**
     * Privilege value: NONE = 0, READ = 1, UPDATE = 2, DELETE = 4,
     * CREATE = 8, or you can OR them together.
     */
    private int value = 0;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get id of the permission.
     * 
     * @return String
     */
    public String getId()
    {
        return this.id;
    } //-- String getId()

    /**
     * Get privilege value: NONE = 0, READ = 1, UPDATE = 2, DELETE
     * = 4, CREATE = 8, or you can OR them together.
     * 
     * @return int
     */
    public int getValue()
    {
        return this.value;
    } //-- int getValue()

    /**
     * Set id of the permission.
     * 
     * @param id
     */
    public void setId( String id )
    {
        this.id = id;
    } //-- void setId( String )

    /**
     * Set privilege value: NONE = 0, READ = 1, UPDATE = 2, DELETE
     * = 4, CREATE = 8, or you can OR them together.
     * 
     * @param value
     */
    public void setValue( int value )
    {
        this.value = value;
    } //-- void setValue( int )

}
